### PR TITLE
Fix:  buffer length error in devices/honeywell.c 

### LINKED ISSUE #1597: Bug:  buffer length error in devices/honeywell.c
in [honeywell_decode](https://github.com/merbanan/rtl_433/blob/master/src/devices/honeywell.c#L82) line 84. 

with verbose set `bitrow_printf` can be called with a length that exceeds  the buffer length of b (80 bits) if called with sufficiently large bitbuffer
 
This is due to the value  of `len` being based off the input bitbuffer  and not the the local buffer [`b`](https://github.com/merbanan/rtl_433/blob/master/src/devices/honeywell.c#L50)

rtl_433   -vvvv   -y '{2048}021e01e1f8c230618197f07be3f000e3fe33fffe00383fe3ffe0007ff88e81e0e7fdc00087c1eff43e39ff8863fc0b7fdc077f33f0018101c7d8c00c038380087b3efcf0f04e0e41e601e609ca0a0c8c0078fc0fdbfe40190831301b003000105fc7878c783fe3c00dd80701801f1cff7f7ffff87ffbfc9f9c1dfbfff1d21fff3f67e60c00b7fa0307fc1c0079003e3031c9fdff010804008ffff0ffffe01ff0063f00fff00001f00000c600707fc1101f1807ffcfcfdbe463e7bbec09be7f801e1fc01cffc1cf1a61fe6397ccf2f0073827c01fffdcfbc3f781effc1f07cfd0ff7bfffb803c3fffffffffffffffff80000000000000000000000000007fffff'

### PR DESCRIPTION
**Pull request by evilpete**
bitrow_printf can be called with a length that exceeds the buffer length of `b` (80 bits) if called with sufficiently large bitbuffer

closes #1597

### CODE REVIEW

File: src/devices/honeywell.c [hunk 1]
```diff
@@ -81,7 +81,7 @@ static int honeywell_decode(r_device *decoder, bitbuffer_t *bitbuffer)
 
     if (len > 50) { // DW11
         if (decoder->verbose)
-            bitrow_printf(b, len, "%s: ", __func__);
+            bitrow_printf(b, (len >80 ? 80 : len) , "%s: ", __func__);
```
Comment (zuckschwerdt) [inline src/devices/honeywell.c:84]: A space after the comparison operator, please ;)

Comment (evilpete) [reply src/devices/honeywell.c]: Done..
